### ISSUE TITLE
Defaulting to `bussines_unit_id` and `created_by_user_id` doesn't work when creating new version

### ISSUE THREAD

**Issue by lukasz-mitka** [FiniteStateInc/finite-state-sdk-python#6]
Tested on version `0.0.5`.
This is how SDK tries to get it: https://github.com/FiniteStateInc/finite-state-sdk-python/blob/a046c31c04f31fa29a14cec790f7d427f474688c/finite_state_sdk/__init__.py#L295

And here's the returned object.

```json5
[
    {
        '_cursor': '{"id":"<id>"}', 
        'id': '<id>', 
        'name': 'test ', 
        'createdAt': 
        '2023-06-20T08:28:03Z', 
        'ctx': {
            'asset': '<id>', 
            'businessUnits': ['<id>'], 
            'products': ['<id>']
        }
    }
]
```

Please fix getting business unit and add user_id.

P.S.
https://github.com/FiniteStateInc/finite-state-sdk-python/blob/a046c31c04f31fa29a14cec790f7d427f474688c/finite_state_sdk/__init__.py#L280
This assumes this will return only one asset. Please validate if there is in fact only one object returned.

**Comment by nickvido** [comment]
Thank you for reporting this.

The method you referenced is `create_new_asset_version_artifact_and_test_for_upload`, which will just return a Test `id`. Did you mean to reference another location?

It seems like you might want one of the other SDK methods to return the User `id`?

**RE: Line 280**
This is correct - it it getting only a single asset for the `create_new_asset_version_artifact_and_test_for_upload` method. I do see that it should be checking that `asset_id` is specified before that, and it is a little unclear because it calls `get_all_assets` but that method will only return one object if the `asset_id` is specified. I'll try to make that more clear.

**Comment by nickvido** [comment]
I opened a PR to work on this, here: https://github.com/FiniteStateInc/finite-state-sdk-python/pull/7

I took a guess that you might be referring to the `get_all_assets` is not returning the `createdBy` user, so I added that in a few of the queries, and also the `__typename` for some queries.

**Comment by nickvido** [comment]
I see it, now. Sorry, adding the group to the query and fixing the code that references it.

**Comment by lukasz-mitka** [comment]
Tested and it's working as expected now.
Thank you @nickvido for quick response!
